### ISSUE TITLE
Upgrade README

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#116]
- Update the README based on what we did for the tool repositories.
- Add Code of Conduct
- Add Contribution Guide

**Comment by thomasyu888** [comment]
* Added [code of conduct](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/CODE_OF_CONDUCT.md) (copied from other nlp repos): 
* Updated README/ [contributing guide](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/CONTRIBUTING.md)
* Auto generated documentation: https://nlpsandbox.github.io/nlpsandbox-client/

Sorry, I was trigger happy and merged a lot of these.  Am trying to push a 0.4.1 release, then we can review everything and push the 1.0.0

**Comment by tschaffter** [comment]
@thomasyu888 Assigning this ticket to you. I don't have required for the README at this point.
