### ISSUE TITLE
Change format of `annotate_note`

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/nlpsandbox-client#119]
https://github.com/nlpsandbox/nlpsandbox-client/blob/540fbfe4fc4ac6adff1be7db5f5593aa5cd86cbd/nlpsandboxclient/client.py#L344

`annotate_note` takes as input a `note`, but this parameter name is a bit misleading in my opinion, as it actually expects a dictionary with one key (`'note'`) and one value (the note itself, in `dict` form), e.g.:

`annotate_note(..., note={'note': {'text': "The patient, Emily Dickinson...", identifier: "1234", patient_id: "1234", note_type: "asdf"}})`

Wouldn't it make more sense instead to just have the `note` parameter directly take a `note` (either as a `dict` or even just as a `Note` object) instead?

Also, the `annotator_type` parameter takes inputs (`date`, `person`, `address`) that are out of line with anything else, as far as a I can tell. Could they be changed to `text_date`, `text_person_name`, and `text_physical_address` to be more in line with the rest of NLP Sandbox?

Of course, this would break the old method and therefore could only be released in a major version update.

**Comment by thomasyu888** [comment]
I think this is something that could be discussed on the API level right?  I've always found it confusing that you don't pass in the Note object for annotation but you must add the note inside of "note".

Also agreed with annotator_type,  but that will be a pretty big change for the controller as well which will take some time.

**Comment by thomasyu888** [comment]
Changing the scope of this ticket and opened this: https://github.com/nlpsandbox/nlpsandbox-client/issues/131
