### ISSUE TITLE
Automatically update client when new API release is available

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#120]
Following the example provided by https://github.com/nlpsandbox/docker-elk/blob/develop/.github/workflows/update.yml

**Comment by thomasyu888** [comment]
It's not that easy as the 'annotator' SDK requires the three annotators merged into one which is currently sitting in a PR.

**Comment by thomasyu888** [comment]
Done.  The entire API is merged into one openapi.json which makes updating much easier.
