### ISSUE TITLE
Fix CI/CD workflow that builds and pushes to Dockerhub

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-client#126]
### Problem description

- See: https://github.com/nlpsandbox/nlpsandbox-client/runs/1993788664?check_suite_focus=true#step:7:22
- Also see on dockerhub: https://hub.docker.com/r/nlpsandbox/cli/tags?page=1&ordering=last_updated

It appears that when I released 0.4.1, it created docker tag `0`, `0.4` and `0.4.1`

#### Expected behavior

Tags should only build that specific version, but it seems to be building multiple.

**Comment by tschaffter** [comment]
What is this command for? Is this linked to the CI/CD workflow that build and publish the image to Docker Hub?

**Comment by thomasyu888** [comment]
@tschaffter Yes, sorry for the lack of description.  I made some edits and added details.

**Comment by tschaffter** [comment]
@thomasyu888 Is fixing this ticket required for the launch?

**Comment by thomasyu888** [comment]
@tschaffter Not required for launch

**Comment by tschaffter** [comment]
Version system in place is intentional.
