### ISSUE TITLE
Change "date", "person", and "address" parameters

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-client#131]
### Is your proposal related to a problem?

From @cascadianblue 

The `annotator_type` parameter takes inputs (date, person, address) that are out of line with anything else, as far as a I can tell. 

### Describe the solution you'd like

Could they be changed to `text_date`, `text_person_name`, and `text_physical_address` to be more in line with the rest of NLP Sandbox?

This will impact the controllers, evaluation code, and client.

**Comment by thomasyu888** [comment]
This would have to be updated:

```
nlp-cli tool annotate-note

**Comment by tschaffter** [comment]
It seems that we have two types of tools:

- This client defines `annotator_type` that takes these values:
  - `date`
  - `person`
  - `address`
- The NLP Sandbox Schemas defines four Tool APIs that are expected to return [Tool.toolType](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/176a553d40a71d6c23e8787e314541583fbe4617/openapi/commons/components/schemas/Tool.yaml#L35) with these values:
  - `nlpsandbox:date-annotator`
  - `nlpsandbox:person-name-annotator`
  - `nlpsandbox:physical-address-annotator`
  - `nlpsandbox:phi-deidentifier`

I would recommend for this client:

- Rename `annotator_type` to `tool_type` (an annotator is a sub-type of tools)
- Use in the client the type values: `nlpsandbox:date-annotator`, etc.

Note that I didn't define `Tool.toolType` as an enum in the schemas. The motivation is that external organizations may come up in the future with their own type of tools that are still compatible with the NLP Sandbox schemas. Obviously this org would also extend the NLP Sandbox Client to add support for their new type of tool.

@thomasyu888 @cascadianblue

**Comment by tschaffter** [comment]
@cascadianblue If applicable, your implementation of the PHI Deidentifier should also rely on `nlpsandbox:date-annotator`, etc.

**Comment by cascadianblue** [comment]
There happens to be a one-to-one correlation of `tool_type` to annotation type. E.g.

`text_physical_address` -> `nlpsandbox:physical-address-annotator`
`text_date` -> `nlpsandbox:date-annotator`

is this necessarily going to always be true for all tool types?

**Comment by cascadianblue** [comment]
> @cascadianblue If applicable, your implementation of the PHI Deidentifier should also rely on `nlpsandbox:date-annotator`, etc.

@tschaffter the phi-deidentifier uses the `annotation type` convention (e.g. `text_date`) in its response when it passes the annotations on to the client: https://github.com/nlpsandbox/nlpsandbox-schemas/blob/5e0e07af21d1faa816425723b7ed17791426cf27/openapi/phi-deidentifier/components/schemas/AnnotationSet.yaml . Should this be changed to the `tool type` convention (e.g. `nlpsandbox:date-annotator`)? I'm not sure how (well) this would work

**Comment by tschaffter** [comment]
> There happens to be a one-to-one correlation of tool_type to annotation type. E.g.
> is this necessarily going to always be true for all tool types?

@cascadianblue It's difficult to confirm. Why?

**Comment by tschaffter** [comment]
> Should this be changed to the tool type convention (e.g. nlpsandbox:date-annotator)? I'm not sure how (well) this would work

This wouldn't work. It's better to have the tool type and name of the output returned loosely coupled instead of rigidly.

@thomasyu888 Let's go with using tool type (e.g. `nlpsandbox:abc`) to identify a type of tool.

**Comment by thomasyu888** [comment]
@tschaffter, just to confirm if you are ok with cli like this

* Evaluate prediction
  ```
  nlp-cli evaluate-prediction     
  Usage: nlp-cli evaluate-prediction [OPTIONS]
  
    Evaluate the performance of a prediction file. Example prediction and
    goldstandard files are found in test/data/new_prediction.json and
    test/data/new_goldstandard.json respectively.
  
  Options:
    --pred_filepath PATH            Prediction filepath  [required]
    --gold_filepath PATH            Gold standard filepath  [required]
    --output PATH                   Specify output json path
    --tool_type [nlpsandbox:date-annotator|nlpsandbox:person-name-annotator|nlpsandbox:physical-address-annotator]
                                    Type of Tool to evaluate.  [required]
    --help                          Show this message and exit.
  ```

* Annotate Note
  ```
  nlp-cli tool annotate-note
  Usage: nlp-cli tool annotate-note [OPTIONS]
  
    Annotate a note with specified annotator
  
  Options:
    --annotator_host TEXT           Annotator host.  [required]
    --note_json PATH                Clinical notes json  [required]
    --output PATH                   Specify output json path
    --tool_type [nlpsandbox:date-annotator|nlpsandbox:person-name-annotator|nlpsandbox:physical-address-annotator]
                                    The type of tool.  [required]
    --help                          Show this message and exit.
  ```

**Comment by tschaffter** [comment]
@thomasyu888 What is saved to the `output` folder? Is the response displayed in the terminal after running the command?

This CLI looks great!

**Comment by thomasyu888** [comment]
@tschaffter Its not a folder, it's the path to the json.  So if you wanted to get the results of an annotation in `json` it would be:

```
nlp-cli tool annotate-note --output /path/to/my/json.json
```
