### ISSUE TITLE
Unclear How to Combine Annotator Schemas

### ISSUE THREAD

**Issue by cascadianblue** [nlpsandbox/nlpsandbox-client#153]
### Problem description

The [contribution documentation](https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/CONTRIBUTING.md#updating-the-sdk-clients) doesn't seem to show specifically how to combine the annotator specifications into one. Therefore I do not know how to do it

**Comment by thomasyu888** [comment]
This is the merged annotators.   There aren't really instructions, just have to build this manually. https://github.com/nlpsandbox/nlpsandbox-schemas/pull/124

**Comment by thomasyu888** [comment]
I updated the contributing guide.
