### ISSUE TITLE
Add scoring code (evaluation) support for id and contact annotators

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-client#156]
### Is your proposal related to a problem?

Contact, Id, covid symptom annotators needs to be added to the evaluation code

- [x] id
- [x] contact

**Comment by tschaffter** [comment]
Depends on:
- https://github.com/nlpsandbox/nlpsandbox/issues/46
- https://github.com/nlpsandbox/nlpsandbox/issues/47

**Comment by tschaffter** [comment]
@thomasyu888 Removing support for covid annotator from the scope of this ticket.

**Comment by tschaffter** [comment]
The generator will generate code for the covid annotator because it's in the schema.

**Comment by thomasyu888** [comment]
@tschaffter This is for the evaluation script code?  I don't think the scoring script is auto generated at all.

**Comment by tschaffter** [comment]
Your right. Assigning to @yy6linda
