### ISSUE TITLE
Update `example-patient-bundles.json` to include other annotators

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-client#160]
### Is your proposal related to a problem?
This file is used with the example `push_dataset.py` code to push a very small fake dataset into the data node to make sure the data node works

**Comment by tschaffter** [comment]
Related to #113.

The bundle data should be ready but we want to start propagating schemas 1.1.2 in an ordered manner. Let's discuss this in our next meeting.

**Comment by tschaffter** [comment]
Done, see https://github.com/nlpsandbox/i2b2-phi-dataset
