### ISSUE TITLE
Replace the term SDK?

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#168]
https://rapidapi.com/blog/api-vs-sdk/

I don't think that we provide a kit of tools, which is often understood by SDK. What we provide is actually an API that let the user interact with NLPSandbox.io services. Here we bridge the public API that we expose to the user to the code automatically generated by the openapi generator.

I'm also thinking to the `import` that a user of the client library needs to add to a notebook or python script. I think that currently the user can use all the public feature that we expose by importing classes that starts with `nlpsasndboxclient.`. Is that correct?

@thomasyu888 Thoughts on this terminology?

**Comment by thomasyu888** [comment]
I use the term SDK from this: https://docker-py.readthedocs.io/en/stable/

**Comment by tschaffter** [comment]
I'm OK with the current naming. I should first spend time using the client, then I will know better whether I feel like a change of package names is required.

**Comment by tschaffter** [comment]
After a second look at the Python client code and see the PHI deidentifier using it, I now prefer to replace `nlpsandboxsdk.*` by `nlpsandbox.*`. This would actually respect the example provided by @thomasyu888 earlier in this ticket regarding docker client implementation. Here are additional thoughts:

- It does not seem to me that the addition of `sdk` solves an issue, for example a conflict with an existing library that would have already been named `nlpsandbox`.
- Most developer will intuitively try to import `nlpsandbox.xyz`, for example `nlpsandbox.model`.
- `nlpsandbox.models.TextDateAnnotation` looks better than the longer version with `sdk`.
