### ISSUE TITLE
Set default branch to main

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#176]
All the other nlpsandbox repository should now have their default branch set to "main". Most developers will expect the main branch to be called "main".

**Comment by thomasyu888** [comment]
@tschaffter I will do this but typically when people are pulling repositories, they don't specify a branch. So by default it pulls down the default branch regardless of which one it is.  Can I have admin access on this repo please?

**Comment by tschaffter** [comment]
As developers start working with other branches, they will need to enter the name of the default branch eventually (e.g. `git checkout main`).

**Comment by thomasyu888** [comment]
@tschaffter When developers work with this, they will have to fork it, and it's their responsibility to keep track of what branches they work on.  That being said, I am fine with the shift to main being the default branch.

**Comment by tschaffter** [comment]
Yes, but we can imagine that they will *unconsciously* try the first few times to go back to the default branch with `git checkout main`, which would not work if our default branch is named differently. It's a tiny contribution to make the work of developers more easy

**Comment by thomasyu888** [comment]
@tschaffter Done.
