### ISSUE TITLE
Document how the user can pass Synapse credential to the Docker image

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#18]

**Comment by thomasyu888** [comment]
There are multiple options.   

* `cli` takes synapse username and password/apikey as parameters
* mount the `~/.syanspeCconfig` to `/root/.synapseConfig`, but this would force people to have a `~/.synapseConfig` file locally.

**Comment by tschaffter** [comment]
> cli takes synapse username and password/apikey as parameters

I guess that it's the easiest solution. But since it's not recommended to enter the credential in clear in the command line, we could recommend to create environment variable SYNAPSE_USERNAME and SYNAPSE_API_TOKEN and import them as environment variables, e.g. `docker run -e SYNAPSE_USERNAME ...`.

```
host$ export PLOP="hello"
host$ echo $PLOP
hello
host$ docker run -it -e PLOP ubuntu bash
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
d72e567cc804: Pull complete
0f3630e5ff08: Pull complete
b6a83d81d1f4: Pull complete
Digest: sha256:bc2f7250f69267c9c6b66d7b6a81a54d3878bb85f1ebb5f951c896d13e6ba537
Status: Downloaded newer image for ubuntu:latest
root@5029fc4d3c9a:/# echo $PLOP
hello
```

Then there are two solutions to use these credentials in the container:

1. The client reads the environment variables and does `syn.login(username=..., api_token=...)` (I forgot the actually variable names) OR

2. Use an initialization script that creates *.synapseConfig* and places it in the user folder (ultimately non-root user), then have the client uses `syn.login()`. I'm using this approach for the 2014 i2b2 data node and could put that in place here too.
https://github.com/Sage-Bionetworks/nlp-sandbox-data-node-i2b2-2014/blob/develop/server/root/etc/cont-init.d/30-get-data#L9-L13

**Comment by thomasyu888** [comment]
I don't really have a strong preference in any of these solutions.  I have implemented all of them for particular projects I'm on to give users the choice to provide synapse login of their choice.  I do however feel that all three of these solutions are a little bit clunky.

**Comment by thomasyu888** [comment]
The documentation is done, but the implementation still needs to be complete.
