### ISSUE TITLE
Example not updated for 1.2.0 Data node

### ISSUE THREAD

**Issue by gkowalski** [nlpsandbox/nlpsandbox-client#195]
### Problem description

The example code https://github.com/nlpsandbox/nlpsandbox-client/blob/main/examples/push_dataset.py has not been updated to support the 1.2.0 data node textPhysicalAddressAnnotations is still referenced. instead of TextLocationAnnotation

**Comment by tschaffter** [comment]
@thomasyu888 Also, what about making the example code using the "sdk" client?

**Comment by thomasyu888** [comment]
@tschaffter The example code does use the `nlpsandbox` client.
