### ISSUE TITLE
Add command to validate client input and output data

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#27]
List of JSON object to validate:

- prediction JSON object for each task
- gold standard JSON object for each task

See how to do this in Python:
https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/blob/develop/tools/validate/validate.py

**Comment by tschaffter** [comment]
Depends on https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/issues/38.
Marking this issue as Blocked until the above task is completed.

**Comment by thomasyu888** [comment]
By using the client to get the annotation stores (goldstandard) and annotation results from the annotators (prediction), we may not need this.  Thoughts @tschaffter ?
