### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#38]
Generating the documentation should help us to visualize what's currently implemented in the client. This visual representation should also help us to identify how best organize the client commands.

I had a look at some tools related to Python documentation (slides 13-15):
https://docs.google.com/presentation/d/1xZiQ59DhVCIcGSfAkNAx_BM9PoGmWdz77Ri1jV-iW1s/edit#slide=id.g7a7294dbf9_0_38

@thomasyu888 Have you worked with these tools?

**Comment by thomasyu888** [comment]
Related to #47

**Comment by tschaffter** [comment]
The doc is now available: https://nlpsandbox.github.io/nlpsandbox-client/
