### ISSUE TITLE
Draft client use cases

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#45]
## Stakeholders

- Developer of a NLP tool
- Developer of the NLP sandbox infrastructure
- User of a NLP tool

### Developer of a NLP tool

A1. Send a NLP tool for evaluation to the NLP Sandbox (cloud environment) using a CLI, either manually or as part of a CI/CD workflow
A2. Show submission history
A3. Check the status of recent submissions (pending, running, completed)
A4. Evaluate the performance of a NLP tool locally. The developer would 1) deploy a data node, 2) deploy a NLP tool, 3) use the client to automate the evaluation process: grab notes from the data node, send note to the NLP tool and receive predictions, get gold standard prediction from the data node, compute the performance. Possibly save NLP tool predictions to data node.
A5. Create and manage resources in a data node: Resources: datasets, FHIR stores, patients, clinical notes, annotations stores, annotations. 

### Developer of the NLP sandbox infrastructure

B1. Use the client to automatically evaluate the performance of a submitted NLP tool. Identical to the use case A4 but run by the NLP Sandbox controller that runs on a data site.

### User of a NLP tool

C1. Add patient information and clinical notes to a data node (same as A5)
C2. Process patient and note information by getting them from the data node and sending them a NLP tool (same as A4 minus the evaluation part)

### Create and manage resources in a data node (A5)

Stakeholders: Developer of a NLP tool, Developer of the NLP sandbox infrastructure, User of a NLP tool

Based on the current Data Node API.

#### Create a dataset

Input: DATASET_ID (human friendly)
Output: dataset object created
Endpoint: `/datasets/DATASET_ID`

#### Create a FHIR store

Input: DATASET_ID and FHIR_STORE_ID (both human friendly)
Output: FHIR store object created
Endpoint:
  - `/datasets/DATASET_ID/fhirStores/FHIR_STORE_ID` OR
  - `DATASET_NAME/fhirStores/FHIR_STORE_ID`

#### Push Patient objects to a FHIR store

Input: DATASET_ID and FHIR_STORE_ID (both human friendly), Patient objects (Python objects, JSON file)
Output: Patient objects created
Endpoint:
  - `/datasets/DATASET_ID/fhirStores/FHIR_STORE_ID/fhir/Patient` OR
  - `FHIR_STORE_NAME/fhir/Patient`

#### Push Note objects to a FHIR store

Input: DATASET_ID and FHIR_STORE_ID (both human friendly), Note objects (Python objects, JSON file)
Output: Note objects created
Endpoint:
  - `/datasets/DATASET_ID/fhirStores/FHIR_STORE_ID/fhir/Note` OR
  - `FHIR_STORE_NAME/fhir/Note`

#### List Patient or Note objects in a store

Input: DATASET_ID and FHIR_STORE_ID (both human friendly)
Output: Patient or Note objects
Endpoint (here for patients):
  - `/datasets/DATASET_ID/fhirStores/FHIR_STORE_ID/fhir/Patient` OR
  - `FHIR_STORE_NAME/fhir/Patient`

#### Create an annotation store

Input: DATASET_ID and ANNOTATION_STORE_ID (both human friendly)
Output: Annotation store object created
Endpoint:
  - `/datasets/DATASET_ID/annotationStores/ANNOTATION_STORE_ID`

#### Push Annotation objects to an Annotation store

Input: DATASET_ID and ANNOTATION_STORE_ID (both human friendly), Annotation objects (Python objects, JSON file)
Output: Annotation objects created
Endpoint:
  - `/datasets/DATASET_ID/annotationStores/ANNOTATION_STORE_ID/annotations` OR
  - `ANNOTATION_STORE_NAME/annotations`

#### List Annotation objects in an Annotation store

Input: DATASET_ID and ANNOTATION_STORE_ID (both human friendly)
Output: Annotation objects
Endpoint:
  - `/datasets/DATASET_ID/annotationStores/ANNOTATION_STORE_ID/annotations` OR
  - `ANNOTATION_STORE_NAME/annotations`

#### Get Note objects

Input: DATASET_ID, FHIR_STORE_ID
Example:
  - DATASET_ID: "2014-i2b2-20201120"
  - FHIR_STORE_ID: "evaluation"

Output: List of Note objects

#### Get Annotation objects

Input: DATASET_ID, ANNOTATION_STORE_ID
  - DATASET_ID: "2014-i2b2-20201120"
  - ANNOTATION_STORE_ID: "evaluation-goldstandard"

Output: List of Annotation objects

#### Save predicted annotation objects

Input: DATASET_ID, ANNOTATION_STORE_ID
  - DATASET_ID: "2014-i2b2-20201120"
  - ANNOTATION_STORE_ID: "evaluation-SUBMISSION_ID"

**Comment by thomasyu888** [comment]
Thanks @tschaffter for these detailed descriptions.  Transferring my thoughts from slack onto here: I think the client should be formatted however the API is formatted. Currently, the API takes as "input parameters" things like `datasetId` and `fhirStoreId`.  Therefore, I am going to decide to structure the python client as such:

```
/datasets/DATASET_ID/fhirStores/FHIR_STORE_ID/fhir/Patient
```

The google healthcare API actually takes `name` as input parameter (An example: https://cloud.google.com/healthcare/docs/reference/rest/v1/projects.locations.datasets.dicomStores/get).  Currently I feel like we have built a hybrid API.  You are taking as input parameters the `datasetId` and `fhirStoreId` but you are returning the full path as `name`.    This makes it slightly confusing to chain rest call together, as it would look something like:

```
datasets = get_datasets()
# {'datasets': [{'name': 'datasets/awesome-dataset'}], .....
for dataset in datasets['datasets']:
    datasetid = dataset['name'].split("/")[1]
    print(datasetid)
    # prints out "awesome-dataset"
    get_dataset(datasetid=datasetid)
```

I'm fine with returning "name" as the response body, but we could potentially think about returning:
`{"name": "awesome-dataset"}` instead of `{"name": "dataset/awesome-dataset"}`.  Im honestly confused, because if you look at this: https://cloud.google.com/compute/docs/reference/rest/v1/acceleratorTypes/get,  it isn't structured like the google heatlhcare API at all.

**Comment by thomasyu888** [comment]
Also it is interesting when you call:
```
curl -X GET "http://10.23.55.45:8080/api/v1/datasets/awesome-dataset" -H  "accept: application/json"
# you get:
{
  "name": "datasets/awesome-dataset"
}
```

Which is exactly what you input in the first place.  Was the plan to fill it out more with metadata as we build the API?

**Comment by tschaffter** [comment]
The property Dataset.name is readOnly and so is not accepted as input. The redocly HTML document renders this properly, but not the API documentation rendered by Flask. I haven't try but I'm wondering if the openapi validation would complain if I remove the requestBody for a POST request. I'll give it a try but this is kind of temporary case as we may add properties to the input dataset schema in the future.

**Comment by thomasyu888** [comment]
> The property [Dataset.name is readOnly](https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/blob/5704310a406ea20f33b712a4b7da7069ee82d3cf/openapi/data-node/components/schemas/Dataset.yaml#L7) and so is not accepted as input. The redocly HTML document renders this properly, but not the API documentation rendered by Flask. I haven't try but I'm wondering if the openapi validation would complain if I remove the requestBody for a POST request. I'll give it a try but this is kind of temporary case as we may add properties to the input dataset schema in the future.

**Comment by thomasyu888** [comment]
[x] create dataset
[x] create fhirstore
[x] create patients
[x] create notes
[x] list patients
[x] list notes
[x] create annotation store
[x] create annotations
[x] list annotations
[x] get annotations
[x] get notes
[x] save predicted annotation objects

[ ] show submission history
[ ] Check the status of recent submissions (

**Comment by thomasyu888** [comment]
> The property [Dataset.name is readOnly](https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/blob/5704310a406ea20f33b712a4b7da7069ee82d3cf/openapi/data-node/components/schemas/Dataset.yaml#L7) and so is not accepted as input. The redocly HTML document renders this properly, but not the API documentation rendered by Flask. I haven't try but I'm wondering if the openapi validation would complain if I remove the requestBody for a POST request. I'll give it a try but this is kind of temporary case as we may add properties to the input dataset schema in the future.

What is the real purpose of doing this rest call?
```
curl -X GET "http://10.23.55.45:8080/api/v1/datasets/awesome-dataset" 
```

Normally, we would get other metadata such as:

```
created_on: ...
labels: ...
etc: ...
```

Are we planning on adding more attributes to be returned?

**Comment by tschaffter** [comment]
> curl -X GET "http://10.23.55.45:8080/api/v1/datasets/awesome-dataset" 

The comment I made about `readOnly: true` for the property Dataset.name was valid for the POST endpoint. For the GET verb, the purpose is to get the dataset object, which include the property `name`. Currently that's the only property that the Dataset schema has. See https://github.com/Sage-Bionetworks/nlp-sandbox-schemas/blob/develop/openapi/data-node/components/schemas/Dataset.yaml.

> Are we planning on adding more attributes to be returned?

Absolutely

**Comment by thomasyu888** [comment]
So, one of my branches lists datasets, annotation stores by name.  The question I have is,

Would it confusing for people to do something like this?

```
def create_annotation_store(datasetname, annotation_storeid)
     .....
    return annotation_store_name

def get_annotation_store(annotation_store_name)
    ....
```

**Comment by tschaffter** [comment]
Do you have in mind the programmatic use of the client or the CLI?

When using the client programmatically, we could request the user to:

1. create of a `Dataset` object, then 
2. call `annotation_store = my_dataset.create_annotation_store(annotation_store_id)`

**Comment by thomasyu888** [comment]
Swagger codegen, and my conversations with Jordan led me to think that it is cleaner to not mix the model classes with the api calls.    That is, typically, you have:

```
class DatasetApi():
    # all api calls related to the dataset API

class Dataset()
    # Object has Dataset attributes"

# function in the client that uses the dataset api to to create dataset
dataset_object = create_dataset("my-dataset-id")
annotation_store = create_annotation_store(dataset_object, annotation_storeid = "my-store-id")
```

I haven't worked on any of the models yet, I've just been working with the json.

**Comment by thomasyu888** [comment]
Most of these are encapsulated in the auto generated data node client. Will open up a new issue to draft new use cases
