### ISSUE TITLE
Publish edge version to PyPi

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox-client#54]
Publish the EDGE release to PyPi, i.e. when pushing to the default branch (`develop`). Having access to the edge version will contribute to accelerate testing of the client.

**Comment by tschaffter** [comment]
Publish to https://test.pypi.org/

**Comment by thomasyu888** [comment]
Be careful when doing this. I'm unsure if there is a way to overwrite a pypi tag

**Comment by tschaffter** [comment]
It would have been nice to publish an "edge" version, but PyPi does not allow to overwrite version, which in generate is an excellent best practice. Instead of relying on an edge version, I'm install the "edge" version from the source code after doing `docker pull` on the branch `develop` in combination with `pip install -e .`.
