### ISSUE TITLE
Created merged annotator client for all three services

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-client#78]
Best way is to merge the three openAPI specs together.

**Comment by tschaffter** [comment]
@thomasyu888 Did you merge the specs manually? Here is a tool that could help us to do that programmatically:

- https://www.npmjs.com/package/openapi-merge (library)
- https://www.npmjs.com/package/openapi-merge-cli (cli that uses the library)

**Comment by thomasyu888** [comment]
I merged it manually as it was pretty simple. I'll take a look at that tool.
