### ISSUE TITLE
Add cli create dataset

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox-client#88]

**Comment by thomasyu888** [comment]
@tschaffter , what are your thoughts on this: https://github.com/nlpsandbox/nlpsandbox-client/blob/develop/nlpsandboxclient/client.py#L63-L66.  Currently i have essentially a "get_or_create" function but I call it "get..."  It is actually this way for convenience to not have to add a conditional workflow for CWL:

1. try to get annotation store
2. If annotation store doesn't exist, create it

That being said, we can definitely split it or rename the function to cause less confusion.

**Comment by tschaffter** [comment]
I think that this design may lead to unexpected behavior and confusion. Typically, a user wants to be alerted if his/her input are incorrect, instead of having the client creating a dataset with the typo and push data to it.
